import streamlit as st
from fpdf import FPDF

def generate_questions(name, position, cv_text):
    base = [
        f"Tell us about your experience in {position}.",
        "What is the most challenging project you worked on?",
        "Describe a situation where you solved a major problem.",
        "What skill makes you stand out?",
        "What achievement are you most proud of?",
        "How do you handle pressure at work?"
    ]

    extra = []
    if "Python" in cv_text:
        extra.append("You mentioned Python — what was the last project you used it in?")
    if "Team" in cv_text:
        extra.append("Tell us about your teamwork experience.")

    return base + extra

def build_pdf(candidate):
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Arial", "B", 18)
    pdf.set_text_color(30, 80, 200)
    pdf.cell(0, 10, f"Interview Questions – {candidate['name']}", ln=True)

    pdf.set_font("Arial", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, f"Position: {candidate['position']}", ln=True)

    pdf.ln(5)

    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Generated Questions:", ln=True)

    pdf.set_font("Arial", "", 13)
    for q in candidate["questions"]:
        pdf.multi_cell(0, 8, f"- {q}")
        pdf.ln(1)

    pdf.ln(10)
    pdf.set_font("Arial", "I", 11)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 10, "Generated by Hirix AI – HR Interview Generator", ln=True, align="C")

    return pdf.output(dest="S").encode("latin-1")

st.title("Hirix AI – HR Interview Generator")

if "candidates" not in st.session_state:
    st.session_state["candidates"] = []

if st.button("➕ Add Candidate"):
    st.session_state["candidates"].append({
        "name": "",
        "position": "",
        "cv_text": "",
        "questions": []
    })

for idx, c in enumerate(st.session_state["candidates"]):
    st.markdown("---")
    st.subheader(f"Candidate #{idx + 1}")

    col1, col2 = st.columns(2)

    with col1:
        c["name"] = st.text_input("Candidate Name", key=f"name_{idx}")
        c["position"] = st.text_input("Position", key=f"position_{idx}")
        cv_file = st.file_uploader("Upload CV", key=f"cv_{idx}")

        if cv_file:
            c["cv_text"] = "PDF uploaded"

        if st.button("Generate Questions", key=f"gen_{idx}"):
            if c["name"] and c["position"] and c["cv_text"]:
                c["questions"] = generate_questions(c["name"], c["position"], c["cv_text"])
            else:
                st.warning("Fill all fields before generating questions.")

    with col2:
        st.markdown("#### Questions")
        if c["questions"]:
            for q in c["questions"]:
                st.markdown(f"- {q}")

            if st.button("📄 Download PDF", key=f"pdf_{idx}"):
                pdf_bytes = build_pdf(c)
                st.download_button(
                    "Download PDF",
                    pdf_bytes,
                    file_name=f"{c['name']}_interview.pdf",
                    mime="application/pdf"
                )
        else:
            st.info("No questions generated yet.")
